
<h3>TEMPORARY ACTION</h3>
<?php
echo CHtml::link('AGL 2004', Yii::app()->createUrl('/m1/gLeave/Leave2004', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2005', Yii::app()->createUrl('/m1/gLeave/Leave2005', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2006', Yii::app()->createUrl('/m1/gLeave/Leave2006', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2007', Yii::app()->createUrl('/m1/gLeave/Leave2007', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2008', Yii::app()->createUrl('/m1/gLeave/Leave2008', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2009', Yii::app()->createUrl('/m1/gLeave/Leave2009', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2010', Yii::app()->createUrl('/m1/gLeave/Leave2010', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2011', Yii::app()->createUrl('/m1/gLeave/Leave2011', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('AGL 2012', Yii::app()->createUrl('/m1/gLeave/Leave2012', array("id" => $model->id)));
echo "<br/>";
echo "<br/>";
echo CHtml::link('Lebaran 2005', Yii::app()->createUrl('/m1/gLeave/lebaran2005', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Lebaran 2006', Yii::app()->createUrl('/m1/gLeave/lebaran2006', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Lebaran 2007', Yii::app()->createUrl('/m1/gLeave/lebaran2007', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Lebaran 2008', Yii::app()->createUrl('/m1/gLeave/lebaran2008', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Lebaran 2009', Yii::app()->createUrl('/m1/gLeave/lebaran2009', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Lebaran 2010', Yii::app()->createUrl('/m1/gLeave/lebaran2010', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Lebaran 2011', Yii::app()->createUrl('/m1/gLeave/lebaran2011', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Lebaran 2012', Yii::app()->createUrl('/m1/gLeave/lebaran2012', array("id" => $model->id)));
echo "<br/>";
echo "<br/>";
echo CHtml::link('Natal 2005', Yii::app()->createUrl('/m1/gLeave/natal2005', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Natal 2006', Yii::app()->createUrl('/m1/gLeave/natal2006', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Natal 2007', Yii::app()->createUrl('/m1/gLeave/natal2007', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Natal 2008', Yii::app()->createUrl('/m1/gLeave/natal2008', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Natal 2009', Yii::app()->createUrl('/m1/gLeave/natal2009', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Natal 2010', Yii::app()->createUrl('/m1/gLeave/natal2010', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Natal 2011', Yii::app()->createUrl('/m1/gLeave/natal2011', array("id" => $model->id)));
echo "<br/>";
echo CHtml::link('Natal 2012', Yii::app()->createUrl('/m1/gLeave/natal2012', array("id" => $model->id)));
echo "<br/>";
